---
- name: "Copy MongoDB Repository File"
  copy:
    src: "../files/{{mongodb_repo}}"
    dest: "/etc/yum.repos.d/{{mongodb_repo}}"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true

- name: "Install MongoDB"
  yum: 
    name: mongodb-enterprise
    state: latest
  become: true

- name: "Create dbpath for Application Database"
  file:
    path: /data/appdb
    state: directory
    owner: mongod
    group: mongod
    mode: 0775

- name: Generate keyfile
  command: "{{ 'openssl rand -base64 756' }}"
  register: keyfile

- name: Write keyfile to file
  copy:
    content: "{{ keyfile.stdout }}"
    dest: /etc/mongod.key
    owner: mongod
    group: mongod
    mode: 0400
  become: true

- name: "Copy mongod configuration file"
  copy:
    src: "../files/mongod.conf"
    dest: "/etc/mongod.conf"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true

- name: "Start mongod for the Application Database"
  service:
    name: mongod
    state: started
    enabled: yes
  become: true

- name: Execute mongo.sh shell script from local directory
  script: "../files/mongo.sh"
  args:
    executable: /bin/bash
